Config = {}

-- General Settings
Config.Debug = false
Config.UseOxInventory = false -- Set to true if you want to use ox_inventory instead of custom system
Config.MaxWeight = 30.0 -- Maximum weight a player can carry
Config.MaxSlots = 42 -- Maximum slots in player inventory
Config.HotbarSlots = 5 -- Number of hotbar slots

-- UI Settings
Config.UISettings = {
    colorTheme = "blue",
    gridSize = "medium",
    showWeight = true,
    showDurability = true,
    showIllegalMarker = true,
    showCategoryColors = true,
    darkMode = true,
    bgOpacity = "40",
    borderStyle = "thin",
    uiStyle = "default"
}

-- Item Categories
Config.Categories = {
    { id = "all", name = "All Items" },
    { id = "weapons", name = "Weapons" },
    { id = "consumables", name = "Consumables" },
    { id = "tools", name = "Tools" },
    { id = "valuables", name = "Valuables" },
    { id = "clothing", name = "Clothing" },
    { id = "medical", name = "Medical" },
    { id = "ammo", name = "Ammunition" },
    { id = "misc", name = "Miscellaneous" }
}

-- Color Themes
Config.ColorThemes = {
    {
        id = "blue",
        name = "Blue",
        primary = "from-blue-600 to-blue-700",
        hover = "from-blue-500 to-blue-600",
        accent = "blue",
    },
    {
        id = "green",
        name = "Green",
        primary = "from-green-600 to-green-700",
        hover = "from-green-500 to-green-600",
        accent = "green",
    },
    {
        id = "purple",
        name = "Purple",
        primary = "from-purple-600 to-purple-700",
        hover = "from-purple-500 to-purple-600",
        accent = "purple",
    },
    {
        id = "amber",
        name = "Amber",
        primary = "from-amber-600 to-amber-700",
        hover = "from-amber-500 to-amber-600",
        accent = "amber",
    },
    {
        id = "red",
        name = "Red",
        primary = "from-red-600 to-red-700",
        hover = "from-red-500 to-red-600",
        accent = "red"
    },
    {
        id = "cyan",
        name = "Cyan",
        primary = "from-cyan-600 to-cyan-700",
        hover = "from-cyan-500 to-cyan-600",
        accent = "cyan",
    }
}

-- Keybindings
Config.Keys = {
    OpenInventory = 'TAB', -- Key to open inventory
    UseItem = 'E', -- Key to use selected item
    DropItem = 'G', -- Key to drop selected item
    SplitItem = 'F', -- Key to split item stack
}

-- Container Settings
Config.Containers = {
    ['trunk'] = {
        label = 'Vehicle Trunk',
        maxWeight = 50.0,
        maxSlots = 42,
        allowedItems = {}, -- Empty means all items allowed
        restrictedItems = {} -- Items that cannot be stored
    },
    ['glovebox'] = {
        label = 'Glovebox',
        maxWeight = 5.0,
        maxSlots = 10,
        allowedItems = {},
        restrictedItems = {'weapon_', 'ammo_'}
    },
    ['stash'] = {
        label = 'Personal Stash',
        maxWeight = 100.0,
        maxSlots = 100,
        allowedItems = {},
        restrictedItems = {}
    }
}

-- Item Durability Settings
Config.Durability = {
    enabled = true,
    degradeRate = 0.1, -- Durability loss per use
    repairItems = {
        ['repair_kit'] = 25, -- Repair kit restores 25% durability
        ['advanced_repair_kit'] = 50 -- Advanced repair kit restores 50% durability
    }
}

-- Item Weight Settings
Config.Weight = {
    enabled = true,
    defaultWeight = 0.1, -- Default weight for items without specified weight
    stackableItems = {
        ['money'] = 0.0,
        ['ammo_9mm'] = 0.01,
        ['ammo_45'] = 0.01,
        ['ammo_rifle'] = 0.02,
        ['bandage'] = 0.1,
        ['water'] = 0.5,
        ['sandwich'] = 0.3
    }
}

-- Illegal Item Settings
Config.IllegalItems = {
    ['weapon_pistol'] = true,
    ['weapon_smg'] = true,
    ['weapon_assaultrifle'] = true,
    ['weapon_carbinerifle'] = true,
    ['weapon_advancedrifle'] = true,
    ['weapon_specialcarbine'] = true,
    ['weapon_bullpuprifle'] = true,
    ['weapon_compactrifle'] = true,
    ['weapon_militaryrifle'] = true,
    ['weapon_heavyrifle'] = true,
    ['weapon_sniperrifle'] = true,
    ['weapon_heavysniper'] = true,
    ['weapon_marksmanrifle'] = true,
    ['weapon_pumpshotgun'] = true,
    ['weapon_sawnoffshotgun'] = true,
    ['weapon_assaultshotgun'] = true,
    ['weapon_bullpupshotgun'] = true,
    ['weapon_musket'] = true,
    ['weapon_heavyshotgun'] = true,
    ['weapon_dbshotgun'] = true,
    ['weapon_autoshotgun'] = true,
    ['weapon_microsmg'] = true,
    ['weapon_smg'] = true,
    ['weapon_assaultsmg'] = true,
    ['weapon_combatpdw'] = true,
    ['weapon_mg'] = true,
    ['weapon_combatmg'] = true,
    ['weapon_gusenberg'] = true,
    ['weapon_minigun'] = true,
    ['weapon_rpg'] = true,
    ['weapon_grenadelauncher'] = true,
    ['weapon_minigun'] = true,
    ['weapon_firework'] = true,
    ['weapon_railgun'] = true,
    ['weapon_hominglauncher'] = true,
    ['weapon_grenade'] = true,
    ['weapon_stickybomb'] = true,
    ['weapon_proximitymine'] = true,
    ['weapon_snowball'] = true,
    ['weapon_pipebomb'] = true,
    ['weapon_ball'] = true,
    ['weapon_molotov'] = true,
    ['weapon_flare'] = true,
    ['weapon_bottle'] = true,
    ['weapon_hatchet'] = true,
    ['weapon_machete'] = true,
    ['weapon_switchblade'] = true,
    ['weapon_wrench'] = true,
    ['weapon_battleaxe'] = true,
    ['weapon_poolcue'] = true,
    ['weapon_golfclub'] = true,
    ['weapon_knuckle'] = true,
    ['weapon_knife'] = true,
    ['weapon_bat'] = true,
    ['weapon_crowbar'] = true,
    ['weapon_golfclub'] = true,
    ['weapon_hammer'] = true,
    ['weapon_hatchet'] = true,
    ['weapon_machete'] = true,
    ['weapon_switchblade'] = true,
    ['weapon_wrench'] = true,
    ['weapon_battleaxe'] = true,
    ['weapon_poolcue'] = true,
    ['weapon_golfclub'] = true,
    ['weapon_knuckle'] = true,
    ['weapon_knife'] = true,
    ['weapon_bat'] = true,
    ['weapon_crowbar'] = true,
    ['weapon_golfclub'] = true,
    ['weapon_hammer'] = true,
    ['weapon_hatchet'] = true,
    ['weapon_machete'] = true,
    ['weapon_switchblade'] = true,
    ['weapon_wrench'] = true,
    ['weapon_battleaxe'] = true,
    ['weapon_poolcue'] = true,
    ['weapon_stone_hatchet'] = true,
    ['weapon_candycane'] = true,
    ['weapon_antique_cavalry'] = true,
    ['weapon_broken_bottle'] = true,
    ['weapon_cs_blade'] = true,
    ['weapon_antique_dagger'] = true,
    ['weapon_hatchet_02'] = true,
    ['weapon_knife_02'] = true,
    ['weapon_knuckle_02'] = true,
    ['weapon_knuckle_03'] = true,
    ['weapon_knuckle_04'] = true,
    ['weapon_knuckle_05'] = true,
    ['weapon_knuckle_06'] = true,
    ['weapon_knuckle_07'] = true,
    ['weapon_knuckle_08'] = true,
    ['weapon_knuckle_09'] = true,
    ['weapon_knuckle_10'] = true,
    ['weapon_knuckle_11'] = true,
    ['weapon_knuckle_12'] = true,
    ['weapon_knuckle_13'] = true,
    ['weapon_knuckle_14'] = true,
    ['weapon_knuckle_15'] = true,
    ['weapon_knuckle_16'] = true,
    ['weapon_knuckle_17'] = true,
    ['weapon_knuckle_18'] = true,
    ['weapon_knuckle_19'] = true,
    ['weapon_knuckle_20'] = true,
    ['weapon_knuckle_21'] = true,
    ['weapon_knuckle_22'] = true,
    ['weapon_knuckle_23'] = true,
    ['weapon_knuckle_24'] = true,
    ['weapon_knuckle_25'] = true,
    ['weapon_knuckle_26'] = true,
    ['weapon_knuckle_27'] = true,
    ['weapon_knuckle_28'] = true,
    ['weapon_knuckle_29'] = true,
    ['weapon_knuckle_30'] = true,
    ['weapon_knuckle_31'] = true,
    ['weapon_knuckle_32'] = true,
    ['weapon_knuckle_33'] = true,
    ['weapon_knuckle_34'] = true,
    ['weapon_knuckle_35'] = true,
    ['weapon_knuckle_36'] = true,
    ['weapon_knuckle_37'] = true,
    ['weapon_knuckle_38'] = true,
    ['weapon_knuckle_39'] = true,
    ['weapon_knuckle_40'] = true,
    ['weapon_knuckle_41'] = true,
    ['weapon_knuckle_42'] = true,
    ['weapon_knuckle_43'] = true,
    ['weapon_knuckle_44'] = true,
    ['weapon_knuckle_45'] = true,
    ['weapon_knuckle_46'] = true,
    ['weapon_knuckle_47'] = true,
    ['weapon_knuckle_48'] = true,
    ['weapon_knuckle_49'] = true,
    ['weapon_knuckle_50'] = true,
    ['weapon_knuckle_51'] = true,
    ['weapon_knuckle_52'] = true,
    ['weapon_knuckle_53'] = true,
    ['weapon_knuckle_54'] = true,
    ['weapon_knuckle_55'] = true,
    ['weapon_knuckle_56'] = true,
    ['weapon_knuckle_57'] = true,
    ['weapon_knuckle_58'] = true,
    ['weapon_knuckle_59'] = true,
    ['weapon_knuckle_60'] = true,
    ['weapon_knuckle_61'] = true,
    ['weapon_knuckle_62'] = true,
    ['weapon_knuckle_63'] = true,
    ['weapon_knuckle_64'] = true,
    ['weapon_knuckle_65'] = true,
    ['weapon_knuckle_66'] = true,
    ['weapon_knuckle_67'] = true,
    ['weapon_knuckle_68'] = true,
    ['weapon_knuckle_69'] = true,
    ['weapon_knuckle_70'] = true,
    ['weapon_knuckle_71'] = true,
    ['weapon_knuckle_72'] = true,
    ['weapon_knuckle_73'] = true,
    ['weapon_knuckle_74'] = true,
    ['weapon_knuckle_75'] = true,
    ['weapon_knuckle_76'] = true,
    ['weapon_knuckle_77'] = true,
    ['weapon_knuckle_78'] = true,
    ['weapon_knuckle_79'] = true,
    ['weapon_knuckle_80'] = true,
    ['weapon_knuckle_81'] = true,
    ['weapon_knuckle_82'] = true,
    ['weapon_knuckle_83'] = true,
    ['weapon_knuckle_84'] = true,
    ['weapon_knuckle_85'] = true,
    ['weapon_knuckle_86'] = true,
    ['weapon_knuckle_87'] = true,
    ['weapon_knuckle_88'] = true,
    ['weapon_knuckle_89'] = true,
    ['weapon_knuckle_90'] = true,
    ['weapon_knuckle_91'] = true,
    ['weapon_knuckle_92'] = true,
    ['weapon_knuckle_93'] = true,
    ['weapon_knuckle_94'] = true,
    ['weapon_knuckle_95'] = true,
    ['weapon_knuckle_96'] = true,
    ['weapon_knuckle_97'] = true,
    ['weapon_knuckle_98'] = true,
    ['weapon_knuckle_99'] = true,
    ['weapon_knuckle_100'] = true,
    ['ammo_9mm'] = true,
    ['ammo_45'] = true,
    ['ammo_rifle'] = true,
    ['ammo_shotgun'] = true,
    ['ammo_smg'] = true,
    ['ammo_sniper'] = true,
    ['ammo_mg'] = true,
    ['ammo_rpg'] = true,
    ['ammo_grenade'] = true,
    ['ammo_stickybomb'] = true,
    ['ammo_proximitymine'] = true,
    ['ammo_snowball'] = true,
    ['ammo_pipebomb'] = true,
    ['ammo_ball'] = true,
    ['ammo_molotov'] = true,
    ['ammo_flare'] = true,
    ['ammo_bottle'] = true,
    ['ammo_hatchet'] = true,
    ['ammo_machete'] = true,
    ['ammo_switchblade'] = true,
    ['ammo_wrench'] = true,
    ['ammo_battleaxe'] = true,
    ['ammo_poolcue'] = true,
    ['ammo_golfclub'] = true,
    ['ammo_knuckle'] = true,
    ['ammo_knife'] = true,
    ['ammo_bat'] = true,
    ['ammo_crowbar'] = true,
    ['ammo_golfclub'] = true,
    ['ammo_hammer'] = true,
    ['ammo_hatchet'] = true,
    ['ammo_machete'] = true,
    ['ammo_switchblade'] = true,
    ['ammo_wrench'] = true,
    ['ammo_battleaxe'] = true,
    ['ammo_poolcue'] = true,
    ['ammo_golfclub'] = true,
    ['ammo_knuckle'] = true,
    ['ammo_knife'] = true,
    ['ammo_bat'] = true,
    ['ammo_crowbar'] = true,
    ['ammo_golfclub'] = true,
    ['ammo_hammer'] = true,
    ['ammo_hatchet'] = true,
    ['ammo_machete'] = true,
    ['ammo_switchblade'] = true,
    ['ammo_wrench'] = true,
    ['ammo_battleaxe'] = true,
    ['ammo_poolcue'] = true,
    ['ammo_stone_hatchet'] = true,
    ['ammo_candycane'] = true,
    ['ammo_antique_cavalry'] = true,
    ['ammo_broken_bottle'] = true,
    ['ammo_cs_blade'] = true,
    ['ammo_antique_dagger'] = true,
    ['ammo_hatchet_02'] = true,
    ['ammo_knife_02'] = true,
    ['ammo_knuckle_02'] = true,
    ['ammo_knuckle_03'] = true,
    ['ammo_knuckle_04'] = true,
    ['ammo_knuckle_05'] = true,
    ['ammo_knuckle_06'] = true,
    ['ammo_knuckle_07'] = true,
    ['ammo_knuckle_08'] = true,
    ['ammo_knuckle_09'] = true,
    ['ammo_knuckle_10'] = true,
    ['ammo_knuckle_11'] = true,
    ['ammo_knuckle_12'] = true,
    ['ammo_knuckle_13'] = true,
    ['ammo_knuckle_14'] = true,
    ['ammo_knuckle_15'] = true,
    ['ammo_knuckle_16'] = true,
    ['ammo_knuckle_17'] = true,
    ['ammo_knuckle_18'] = true,
    ['ammo_knuckle_19'] = true,
    ['ammo_knuckle_20'] = true,
    ['ammo_knuckle_21'] = true,
    ['ammo_knuckle_22'] = true,
    ['ammo_knuckle_23'] = true,
    ['ammo_knuckle_24'] = true,
    ['ammo_knuckle_25'] = true,
    ['ammo_knuckle_26'] = true,
    ['ammo_knuckle_27'] = true,
    ['ammo_knuckle_28'] = true,
    ['ammo_knuckle_29'] = true,
    ['ammo_knuckle_30'] = true,
    ['ammo_knuckle_31'] = true,
    ['ammo_knuckle_32'] = true,
    ['ammo_knuckle_33'] = true,
    ['ammo_knuckle_34'] = true,
    ['ammo_knuckle_35'] = true,
    ['ammo_knuckle_36'] = true,
    ['ammo_knuckle_37'] = true,
    ['ammo_knuckle_38'] = true,
    ['ammo_knuckle_39'] = true,
    ['ammo_knuckle_40'] = true,
    ['ammo_knuckle_41'] = true,
    ['ammo_knuckle_42'] = true,
    ['ammo_knuckle_43'] = true,
    ['ammo_knuckle_44'] = true,
    ['ammo_knuckle_45'] = true,
    ['ammo_knuckle_46'] = true,
    ['ammo_knuckle_47'] = true,
    ['ammo_knuckle_48'] = true,
    ['ammo_knuckle_49'] = true,
    ['ammo_knuckle_50'] = true,
    ['ammo_knuckle_51'] = true,
    ['ammo_knuckle_52'] = true,
    ['ammo_knuckle_53'] = true,
    ['ammo_knuckle_54'] = true,
    ['ammo_knuckle_55'] = true,
    ['ammo_knuckle_56'] = true,
    ['ammo_knuckle_57'] = true,
    ['ammo_knuckle_58'] = true,
    ['ammo_knuckle_59'] = true,
    ['ammo_knuckle_60'] = true,
    ['ammo_knuckle_61'] = true,
    ['ammo_knuckle_62'] = true,
    ['ammo_knuckle_63'] = true,
    ['ammo_knuckle_64'] = true,
    ['ammo_knuckle_65'] = true,
    ['ammo_knuckle_66'] = true,
    ['ammo_knuckle_67'] = true,
    ['ammo_knuckle_68'] = true,
    ['ammo_knuckle_69'] = true,
    ['ammo_knuckle_70'] = true,
    ['ammo_knuckle_71'] = true,
    ['ammo_knuckle_72'] = true,
    ['ammo_knuckle_73'] = true,
    ['ammo_knuckle_74'] = true,
    ['ammo_knuckle_75'] = true,
    ['ammo_knuckle_76'] = true,
    ['ammo_knuckle_77'] = true,
    ['ammo_knuckle_78'] = true,
    ['ammo_knuckle_79'] = true,
    ['ammo_knuckle_80'] = true,
    ['ammo_knuckle_81'] = true,
    ['ammo_knuckle_82'] = true,
    ['ammo_knuckle_83'] = true,
    ['ammo_knuckle_84'] = true,
    ['ammo_knuckle_85'] = true,
    ['ammo_knuckle_86'] = true,
    ['ammo_knuckle_87'] = true,
    ['ammo_knuckle_88'] = true,
    ['ammo_knuckle_89'] = true,
    ['ammo_knuckle_90'] = true,
    ['ammo_knuckle_91'] = true,
    ['ammo_knuckle_92'] = true,
    ['ammo_knuckle_93'] = true,
    ['ammo_knuckle_94'] = true,
    ['ammo_knuckle_95'] = true,
    ['ammo_knuckle_96'] = true,
    ['ammo_knuckle_97'] = true,
    ['ammo_knuckle_98'] = true,
    ['ammo_knuckle_99'] = true,
    ['ammo_knuckle_100'] = true
}

-- Item Images (you can customize these URLs)
Config.ItemImages = {
    ['phone'] = 'https://i.gyazo.com/855fff443d61d880045f5ee7e1440db5.png',
    ['bandage'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bandage_item-DR8T0b1A0Ne540OgkUkyR19VQfDEGO.png',
    ['water'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/water_bottle_item-uaB2JNkjnSVE4MeAgQaOtpjPe63CIf.png',
    ['weapon_pistol'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pistol_item-vZQ8XUwCXvng8VXAoS9rriWLwu6PD6.png',
    ['ammo_9mm'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ammo_9mm_item-IprXpqXX2f1sEhda3XzJkfCp0OGJyU.png',
    ['lockpick'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lockpick_item-iequCFnWiV7ywTeuntIKskrf7c4n16.png',
    ['money'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/cash_icon-aoFhwPnNQDJMrU98zNt2BAQH65Pv7x.png',
    ['tshirt'] = 'https://cdn3.iconfinder.com/data/icons/clothing-set-4/64/tshirt-other-512.png',
    ['firstaid'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/first_aid_kit_item-gPSbMKf9THF0qEPwVh31v0iXjlSVPm.png',
    ['goldbar'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/goldbar_inventory_item-qL2NbeJ3FRnxDm2Mg0YVmzaEAqYkuv.png',
    ['weapon_assaultrifle'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/assault_rifle_item-iiLdD3fMRUiCHk6DnuPseNCGnOVToX.png',
    ['burger'] = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/burger_item-jRAminnmsZZHX6v7QLr7vy9vcnrLv0.png'
}

-- Default item data (for items not in QB-Core)
Config.DefaultItems = {
    ['phone'] = {
        label = 'Phone',
        weight = 0.5,
        type = 'item',
        image = 'phone.png',
        unique = false,
        useable = true,
        shouldClose = true,
        combinable = nil,
        description = 'A smartphone with various apps'
    },
    ['bandage'] = {
        label = 'Bandage',
        weight = 0.1,
        type = 'item',
        image = 'bandage.png',
        unique = false,
        useable = true,
        shouldClose = true,
        combinable = nil,
        description = 'Used to stop bleeding and heal minor wounds'
    },
    ['water'] = {
        label = 'Water Bottle',
        weight = 0.5,
        type = 'item',
        image = 'water.png',
        unique = false,
        useable = true,
        shouldClose = true,
        combinable = nil,
        description = 'Refreshing water to quench your thirst'
    }
}
